[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
piggybank = "LvPibsi1V7z71Nmqt3pnafDBgaoeMhiwNVDYMdYc2tG"

[programs.devnet]
piggybank = "LvPibsi1V7z71Nmqt3pnafDBgaoeMhiwNVDYMdYc2tG"

[programs.mainnet]
piggybank = "LvPibsi1V7z71Nmqt3pnafDBgaoeMhiwNVDYMdYc2tG"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
